#!/bin/bash

CONDA_ENV_NAME="kraken" # name that will be used for the conda environment to activate whenever using Cerberus/KrakenTools
KRAKEN_PATH="/global/home/groups/co_nuclear/HxF_tools/KrakenTools_HxF"
CERBERUS_PATH="/global/home/groups/co_nuclear/HxF_tools/Cerberus_HxF"

# Load necessary modules
echo "Loading modules..."
module unload python gcc cmake nano
module load gcc/13.2.0 openmpi cmake/3.27.7 nano

# Install Miniconda if not installed
if [ ! -d "$HOME/miniconda3" ]; then
    echo "Miniconda not found. Installing Miniconda..."
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda3
    rm miniconda.sh
    export PATH="$HOME/miniconda3/bin:$PATH"
    conda init
    source ~/.bashrc
else
    export PATH="$HOME/miniconda3/bin:$PATH"
    source $HOME/miniconda3/etc/profile.d/conda.sh
fi

# Create custom conda directory in scratch folder
SCRATCH="/global/scratch/users/$USER"
echo "Making new conda directory for packages in: $SCRATCH/conda..."
mkdir -p $SCRATCH/conda
conda config --add envs_dirs $SCRATCH/conda
mkdir -p $SCRATCH/conda/pkgs
conda config --add pkgs_dirs $SCRATCH/conda/pkgs

# Add conda-forge channel
conda config --add channels conda-forge

# Create conda environment and activate it
echo "Removing old $CONDA_ENV_NAME conda environment..."
conda deactivate
conda env remove -n $CONDA_ENV_NAME
rm -rf $SCRATCH/conda/$CONDA_ENV_NAME

echo "Creating new $CONDA_ENV_NAME conda environment..."
conda create -y --prefix $SCRATCH/conda/$CONDA_ENV_NAME python=3.11

echo "Activating $CONDA_ENV_NAME conda environment..."
conda activate $CONDA_ENV_NAME

# Install packages in new environment
echo "Installing Python packages..."
conda install -y pip ipykernel
pip install --no-cache-dir serpentTools numpy scipy pandas matplotlib mpi4py ipython seaborn joblib

# Add the conda environment to Jupyter Notebook
ipython kernel install --user --name=$CONDA_ENV_NAME

# Add Cerberus and KrakenTools libraries
conda install -y conda-build
conda develop $CERBERUS_PATH
conda develop $KRAKEN_PATH

# Test if the installation worked
conda deactivate
conda activate $CONDA_ENV_NAME
python -c "import cerberus; print('\tTest OK');"
